#!/bin/bash
#
#------------------------------------------------------------------------------
# File:         call-sleep
#
# Location:     /etc/cron.hourly/call-sleep
#
# Description:  Calls sleep.sh, to initiate a shutdown if certain criteria are met.
#
# Usage:        Run automatically from a cron directory.
#
# Requires:     sleep.sh
#
# Revisions:    2020-09-19 - (Mad About Brighton) Created
#
# References:   https://madaboutbrighton.net
#
# Notes:        This file deliberately has no file extension to enable it to be run 
#               automatically from a cron directory.
#------------------------------------------------------------------------------

sleep.sh -v